#!/bin/bash
# (ar)ch (pa)ckages - a generic package tasks wrapper script for Arch Linux

help_prnt () {
  echo ""${0##*/}" [option] [*package] - a generic package tasks wrapper script
  -e, --explicit - install a package as explicit
  -g, --get      - get/download package upgrade(s) : -G get pkg upgrades all
  -i, --install  - install a package               : -I install as dependency
  -l, --list     - list package files              : -L list pkgs installed
  -o, --owns     - owning package of a file
  -n, --info     - information for a package
  -q, --query    - query for an installed package  : -Q query w/ description
  -r, --remove   - remove a pkg and its deps       : -R force, no argue orphs
  -s, --search   - search for a package            : -S search w/ description
  -u, --upgrade  - upgrade system                  : -U upgrade AUR
  -y, --sync     - sync package db"; }

# Non-root user define sudo
if (( $EUID )); then
  sudo=sudo; fi

case $1 in
  -e | --explicit )
    shift; [ "$@" ] || exit 1; $sudo pacman -S --asexplicit "$@" ;;
  -g | --get )
    shift; [ "$@" ] || exit 1; $sudo pacman -Sw "$@" ;;
  -G | --getup )
    $sudo pacman -Syuw ;;
  -h | --help )
    help_prnt ;;
  -i | --install )
    shift; [ "$@" ] || exit 1
    pre="[a-z,A-Z,0-9,@,/,\.\_\+\-]*pkg.tar[.]\?\(gz\|xz\|bz2\|lrz\|lzo\|Z\)\?"
    pkgoff=$(echo "$@" | sed "s/$pre//g")
    pkgloc=$(echo "$@" | grep -o "$pre")
      [ -n "$pkgoff" ] &&       trizen -S $pkgoff
      [ -n "$pkgloc" ] && $sudo pacman -U $pkgloc ;;
  -I | --depinst )
    shift; [ "$@" ] || exit 1
    pre="[a-z,A-Z,0-9,@,/,\.\_\+\-]*pkg.tar[.]?\(gz\|xz\|bz2\|lrz\|lzo\|Z\)?"
    pkgoff=$(echo "$@" | sed "s/$pre//g")
    pkgloc=$(echo "$@" | grep -o "$pre")
      [ -n "$pkgoff" ] && $sudo pacman -S --asdeps $pkgoff
      [ -n "$pkgloc" ] && $sudo pacman -U --asdeps $pkgloc ;;
  -l | --list )
    shift; [ "$@" ] || exit 1; pacman -Qql "$@" ;;
  -L | --pkglist )
    date=$(date +%F)
    pacman -Qqe | grep -v "$(pacman -Qqm)" > pkglist-off_${date}.txt
    pacman -Qqm                            > pkglist-loc_${date}.txt
    echo "pkglists-built: pkglist-off_${date}.txt, pkglist-loc_${date}.txt" ;;
  -o | --own )
    shift; [ "$@" ] || exit 1; pacman -Qo  "$@" ;;
  -n | --info )
    shift; [ "$@" ] || exit 1
    trizen -Si "$@"   ;;
  -q | --query )
    shift; [ "$@" ] || exit 1
    for p in $@; do
      pacman -Qqs "$p";done ;;
  -Q | --Query )
    shift; [ "$@" ] || exit 1
    for p in $@; do
      pacman -Qi  "$p";done ;;
  -r | --remove )
    shift
    if [ "$#" -eq 0 ]; then
      extrpkg=$(pacman -Qtdq)
      [ "$extrpkg" ] && $sudo pacman -Rcs $extrpkg
    else
      $sudo pacman -Rs "$@"; fi ;;
  -R | --forcerm )
    shift; [ "$@" ] || exit 1; $sudo pacman -Rdd "$@" ;;
  -s | --search )
    shift; [ "$@" ] || exit 1
    trizen -Ssq "$@" ;;
  -S | --Search )
    shift; [ "$@" ] || exit 1
    trizen -Ss "$@"  ;;
  -u | --upgrade )
    $sudo pacman -Syu ;;
  -U | --upaur )
    trizen -Syu --aur --devel ;;
  -y | --sync )
    $sudo pacman -Syy ;;
  * ) help_prnt       ;;
esac
